### ISSUE TITLE
Grafana Setup

### ISSUE THREAD

**Issue by Ashenmaster** [Ashenmaster/pandora#6]
# Description
Grafana needs to report the following metrics:
- Remaining disk space
- Network usage
- CPU Usage
- Temperature
- Uptime
- Logged in  users
-  Speedtest results

# Task List
- [x] Configure telegraf to capture relevant data
- [x] Setup modules in grafana to capture data from telegraf
- [x] Create dashboard to display data
